### ISSUE TITLE
Composition Barplot Top 10 Colors cuts labels off after Phylum level

### ISSUE THREAD

**Issue by MaxxiKing** [tbj128/mian#5]
When viewing data with composition barplot the "top 10 labels" get cut off at phylum level.
![image](https://user-images.githubusercontent.com/29151748/59674791-4b08db80-91c4-11e9-9b3e-ff384a50249b.png)

**Comment by tbj128** [comment]
Thanks for your feedback! Commit fbfb37d adds dynamic resizing of the legend width based on the number of characters of the legend content so the labels should no longer get cut-off.

This commit has now been rolled out to production. Please re-open if you still encounter this issue.
